#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm --prefix webapp run format:check || exit 1
npm --prefix mobileapp run format:check || exit 1
cargo fmt --check --manifest-path server/Cargo.toml || exit 1
